### ISSUE TITLE
JRuby 9k compatibility

### ISSUE THREAD

**Issue by davidpgero** [lenny/log4jruby#14]
Hi there, 

I'd like to use log4jruby to my project. 
The log4jruby 2.0.0.rc1..3 make a strange error. With log4jruby 1.0.0.rc1 works well. 

I attached the error below. 

JRuby, 9.0.4.0
log4jruby, 2.0.0.rc1..3

```
ruby-9.0.4.0@analogy/gems/log4jruby-2.0.0.rc3-java/lib/log4jruby/logger.rb) ~[na:na]
	at home.gdp.$_dot_rvm.gems.jruby_minus_9_dot_0_dot_4_dot_0_at_40_analogy.gems.log4jruby_minus_2_dot_0_dot_0_dot_rc3_minus_java.lib.log4jruby.logger.RUBY$method$tracing?$0(/home/gdp/.rvm/gems/jruby-9.0.4.0@analogy/gems/log4jruby-2.0.0.rc3-java/lib/log4jruby/logger.rb:153) ~[na:na]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:116) ~[na:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:146) ~[na:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:189) ~[na:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129) ~[na:na]
	at home.gdp.$_dot_rvm.gems.jruby_minus_9_dot_0_dot_4_dot_0_at_40_analogy.gems.log4jruby_minus_2_dot_0_dot_0_dot_rc3_minus_java.lib.log4jruby.logger.invokeOther16:tracing?(/home/gdp/.rvm/gems/jruby-9.0.4.0@analogy/gems/log4jruby-2.0.0.rc3-java/lib/log4jruby/logger.rb) ~[na:na]
	at home.gdp.$_dot_rvm.gems.jruby_minus_9_dot_0_dot_4_dot_0_at_40_analogy.gems.log4jruby_minus_2_dot_0_dot_0_dot_rc3_minus_java.lib.log4jruby.logger.RUBY$method$tracing?$0(/home/gdp/.rvm/gems/jruby-9.0.4.0@analogy/gems/log4jruby-2.0.0.rc3-java/lib/log4jruby/logger.rb:153) ~[na:na]
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:116) ~[na:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:146) ~[na:na]
```

**Comment by lenny** [comment]
Hmm.. Have to look at this further. Getting a bunch of spec failures with jruby-9.0.5.0.

**Comment by lenny** [comment]
The log4jruby implementation currently depends on caching Log4Jruby::Logger instances inside of log4j.Logger instances. Seems like that strategy does not currently work in jruby-9000. Not sure if it's a bug or intended. I'll have to go to the JRuby list to find out.

```
require 'test/unit'
require 'test/unit/ui/console/testrunner'

Java::java.lang.Object.class_eval { attr_accessor :foo }

class Example < Test::Unit::TestCase
  def test_ok_with_ruby_hash
    map = {}
    o = Java::java.lang.Object.new
    o.foo = 'FOO'
    map['key'] = o
    assert_same(map['key'], o)
    assert_equal(o.foo, o.foo)
    assert_equal(map['key'].foo, o.foo)
  end

  def test_not_ok_with_java_map
    map = Java::java.util.HashMap.new
    Java::java.lang.Object.class_eval { attr_accessor :foo }
    o = Java::java.lang.Object.new
    o.foo = 'FOO'
    map['key'] = o
    assert_same(map.get('key'), o)
    assert_equal(o.foo, o.foo)
    assert_equal(map['key'].foo, o.foo)
  end
end

Test::Unit::UI::Console::TestRunner.run(Example)
```

**Comment by davidpgero** [comment]
Oh, I forget to run tests before open the issue and share its result for easier reproduce.
Thank you for your investigation!

**Comment by lenny** [comment]
Alternate demo code:

```
# demo.rb
Java::java.lang.Object.class_eval { attr_accessor :foo }
java_list = Java::java.util.ArrayList.new
ruby_list = []
o = Java::java.lang.Object.new
o.foo = 'FOO'
java_list << o
ruby_list << o
raise 'expected o.foo to == FOO' unless o.foo == 'FOO'
unless o.equal?(ruby_list.first) && o.equal?(java_list.first)
  raise 'expected o to be same object as ruby_list.first and java_list.first'
end
raise 'expected ruby_list.first.foo to == FOO' unless ruby_list.first.foo == 'FOO'
raise 'expected java_list.first.foo to == FOO' unless java_list.first.foo == 'FOO'
```
```
bash-3.2$ ruby demo.rb 
RuntimeError: expected java_list.first.foo to == FOO
  <top> at demo.rb:13
```

**Comment by headius** [comment]
JRuby 9.0.5.0 does not by default preserve instance variables and singleton objects attached to Java objects. You can enable this behavior on a class-by-class basis by setting SomeJavaClass.__persistent__ = true, as detailed in this wiki article: https://github.com/jruby/jruby/wiki/Persistence

**Comment by lenny** [comment]
That explains it. Thanks.

**Comment by gordonrs** [comment]
@lenny Is there an ETA on when a fix for this will be merged in? Thanks.

**Comment by lenny** [comment]
I just pushed up log4jruby-2.0.1. Tests all pass now with jruby 9.0.5.0. Let me know if you run into additional issues.

**Comment by gordonrs** [comment]
@lenny So far so good! Thank you sir.

**Comment by davidpgero** [comment]
It works for me too. Thank you!
