### ISSUE TITLE
Deadlock Issue

### ISSUE THREAD

**Issue by ananthka** [lenny/log4jruby#2]
Hi,

We have a multi threaded application which is trying to create a logger , some times we are getting in to the issue of deadlock 

at org.jruby.RubyHash.internalGetEntry(RubyHash.java:540)
	at org.jruby.RubyHash.internalGet(RubyHash.java:535)
	at org.jruby.RubyHash.op_aref(RubyHash.java:1070)
	at org.jruby.RubyHash$INVOKER$i$1$0$op_aref.call(RubyHash$INVOKER$i$1$0$op_aref.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at rubyjit.Log4jruby::Logger$$\=\{\}_A79F70310D0FBA26CF84810DACC4642C03A359F51155181041.__file__(/usr/local/jruby-1.7.3/lib/ruby/gems/shared/gems/log4jruby-1.0.2-java/lib/log4jruby/logger.rb:38)
	at rubyjit.Log4jruby::Logger$$\=\{\}_A79F70310D0FBA26CF84810DACC4642C03A359F51155181041.__file__(/usr/local/jruby-1.7.3/lib/ruby/gems/shared/gems/log4jruby-1.0.2-java/lib/log4jruby/logger.rb)

**Comment by lenny** [comment]
Replaced PR3 with https://github.com/lenny/log4jruby/issues/5

**Comment by lenny** [comment]
https://github.com/lenny/log4jruby/issues/3 has been merged.

**Comment by lenny** [comment]
Additional related changes: https://github.com/lenny/log4jruby/pull/8
