### ISSUE TITLE
No backtraces from Ruby errors with Rails/JRuby < 9.3.x

### ISSUE THREAD

**Issue by lenny** [lenny/log4jruby#27]
Seems like Rails (at least 4.2 and 5.1) is somehow interfering with [LegacyShimFormatter#call(_severity, _time, progname, msg)](https://github.com/lenny/log4jruby/blob/master/lib/log4jruby/support/legacy_shim_formatter.rb).  The `msg` argument is being stringified.

```
> ruby -v
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.292-b10 on 1.8.0_292-b10 +jit [darwin-x86_64]
```

Without Rails - last argument is not stringified and remains an instance_of?(::Exception)
```
> irb
irb(main):004:0> begin; raise 'foo'; rescue => e; end
irb(main):006:0> Log4jruby::Logger.root.formatter.call(nil, nil, 'prog', e)
=> "-- prog: foo (RuntimeError)\n\t(irb):1:in `<eval>'\n\torg/jruby/RubyKernel.java:995:in `eval'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/workspace.rb:87:in `evaluate'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/context.rb:380:in `evaluate'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:489:in `block in eval_input'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:623:in `signal_status'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:486:in `block in eval_input'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/ruby-lex.rb:246:in `block in each_top_level_statement'\n\torg/jruby/RubyKernel.java:1316:in `loop'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/ruby-lex.rb:232:in `block in each_top_level_statement'\n\torg/jruby/RubyKernel.java:1138:in `catch'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/ruby-lex.rb:231:in `each_top_level_statement'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:485:in `eval_input'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:395:in `block in start'\n\torg/jruby/RubyKernel.java:1138:in `catch'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:394:in `start'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/bin/irb:13:in `<main>'"
```

With Rails - last param is stringified

```
> bin/rails c
irb(main):002:0> Log4jruby::Logger.root.formatter.call(nil, nil, 'prog', e)
=> "-- prog: foo"

irb(main):006:0>  Log4jruby::Logger.root.formatter.class
=> Log4jruby::Support::LegacyShimFormatter
```

but instantiating a new instance works as expected

```
irb(main):004:0> Log4jruby::Support::LegacyShimFormatter.new.call(nil, nil, 'prog', e)
=> "-- prog: foo (RuntimeError)\n\t(irb):1:in `<eval>'\n\torg/jruby/RubyKernel.java:995:in `eval'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/workspace.rb:87:in `evaluate'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/context.rb:380:in `evaluate'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:489:in `block in eval_input'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:623:in `signal_status'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:486:in `block in eval_input'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/ruby-lex.rb:246:in `block in each_top_level_statement'\n\torg/jruby/RubyKernel.java:1316:in `loop'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/ruby-lex.rb:232:in `block in each_top_level_statement'\n\torg/jruby/RubyKernel.java:1138:in `catch'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb/ruby-lex.rb:231:in `each_top_level_statement'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:485:in `eval_input'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:395:in `block in start'\n\torg/jruby/RubyKernel.java:1138:in `catch'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/stdlib/irb.rb:394:in `start'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:62:in `start'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:17:in `start'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:97:in `perform'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'\n\t/Users/lenny/.rbenv/versions/jruby-9.1.17.0/lib/ruby/gems/shared/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<main>'\n\torg/jruby/RubyKernel.java:956:in `require'\n\tbin/rails:4:in `<main>'"
```

**Comment by lenny** [comment]
[ActiveSupport::TaggedLogging extends the formatter](https://github.com/rails/rails/blob/fad0c6b/activesupport/lib/active_support/tagged_logging.rb#L81-L93) with a [new implementation of call](https://github.com/rails/rails/blob/fad0c6b899ba786994c506f11f587e29d7bf9c2d/activesupport/lib/active_support/tagged_logging.rb#L31-L33) that stringifies the `msg` argument. 

```
module TaggedLogging
    module Formatter # :nodoc:
      # This method is invoked when a log event occurs.
      def call(severity, timestamp, progname, msg)
        super(severity, timestamp, progname, "#{tags_text}#{msg}")
      end
```

So using e.g. `config.logger =  ActiveSupport::TaggedLogging.new(Log4jruby::Logger.get('SomeApp'))` will prevent using a `formatter` to customize the output of exceptions.
